#pragma once

#define ZERO_DEVICE 0x8000

#define IOCTL_ZERO_GET_STATS CTL_CODE(ZERO_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ZERO_ZERO_STATS CTL_CODE(ZERO_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)

typedef struct _ZeroStats
{
	LONG64 BytesRead;
	LONG64 BytesWritten;
}ZeroStats;